# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package definition and install deps
COPY package*.json ./
RUN npm install --production=false

# Copy all source files
COPY . .

# Build the project
env TS_NODE_PROJECT=tsconfig.json
RUN npm run build

# Prune dev deps
RUN npm prune --production

# Expose default port if needed (not required for stdio)
# ENTRYPOINT for stdio
ENTRYPOINT ["node", "dist/say-hello.js"]
